services:
  - type: web
    name: hotel-management-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://admin:admin123@hotel-management.5ab7zru.mongodb.net/hotel-management?retryWrites=true&w=majority&appName=hotel-management
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_here_change_in_production_123456789
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: http://localhost:3000
